### ISSUE TITLE
[CLASSIC][TBC][WOTLK] Paladin Class "Resurrection" Quests

### ISSUE THREAD

**Issue by Grz3s** [cmangos/issues#1678]
Im in final stage of removing "deathState" from creatures.. and here we have final 4 quests where this "temp solution" is used..
Here some info":
q.1786 'The Tome of Divinity' - humans  (creature: Henze Faulk)
q.1783 'The Tome of Divinity' - dwarfs    (creature: Narm Faulk)
q.9600 'Redemption' - Draenei   (creature: Young Furbolg Shaman)
q.9685 'Redeeming the Dead' - Blood Elfs  (creature: Blood Knight Stillblade)

Ive got all quests already redone.. + all creatures involved corrected... 
And here my questions:

- My oldest data for involved creatures,, comes from 3.3.0 sniffs - does anyone have any older data to compare?
- sd2 script (npc_redemption_target) using one "text" for all 4 quests...There is smth wrong with it. I can't even find source of it (made up?) ... I already corrected dwarfs text (source showed diff one) - maybe someone has data to confirm what text is used in other 3?

I'll wait few days ... who knows.. maybe someone have smth :)...

BTW this is how new ver will work:
https://youtu.be/0NthJEBAdHI

**Comment by cala** [comment]
No data on my side, sorry. It is even possible that the Classic versions were slightly different before the introduction of two more races that can be paladin in TBC (though it would surprise me).

**Comment by Grz3s** [comment]
all what i really need is to check older than 3.3.0 sniffs for:
Elwynn Forest - Henze Faulk 6172
Dun Morogh - Narm Faulk 6177
if anything in UnitFlags or DynamicFlags was changed.

**Comment by bdebaere** [comment]
What's wrong with deathstate if you don't mind me asking?

**Comment by evil-at-wow** [comment]
I should have data in my archives for that quest done with a draenei paladin. I'm not sure what patch exactly, but my guess is this was around February 2009, so that would be patch 3.0.9. Certainly WoTLK. Does that help?

**Comment by Grz3s** [comment]
it will... koz that will give me text used there... + all flags for that creature
@bdebaere 
because its not how it was done originaly...  and sniffs shows smth diff.

**Comment by evil-at-wow** [comment]
As I expected, I have some data for a draenei paladin in my archives. It was captured with client version 3.0.9 build 9551, so keep this in mind when you interpret packet structures and fields below (I was too lazy to do that :wink:).

I've also dumped all relevant packets in that quest, in order, or at least as far as I could see. They start when the Young Furbolg Shaman is first seen by my client, until the NPC is removed again.
I guess this might be useful to someone, say if you want to know where exactly the resurrected Young Furbolg Shaman runs to eventually. The packets are an offset in hex - raw data as hex bytes - ASCII text.

```
SMSG_COMPRESSED_UPDATE_OBJECT
GUID = 0xf1300044862d1940
Position (x y z o) = (-2444.9 -12205.1 32.8857 4.27606)
Update field 0 = 0x40192d86
Update field 1 = 0x440030f1
Update field 2 = 0x09000000 [Type = 9]
Update field 3 = 0x86440000 [Entry = 17542]
Update field 4 = 0x0000803f [Scale = 1.0]
Update field 22 = 0x00020200 [UNIT_FIELD_BYTES_0]
Update field 23 = 0x01000000 [Health = 1]
Update field 26 = 0x64000000 [Power3 = 100]
Update field 27 = 0x64000000 [Power4 = 100]
Update field 28 = 0x40420f00 [Power5 = 1000000]
Update field 31 = 0xba000000 [Max Health = 186]
Update field 32 = 0xbf000000 [Max Power1 = 191]
Update field 34 = 0x64000000 [Max Power3 = 100]
Update field 35 = 0x64000000 [Max Power4 = 100]
Update field 36 = 0x40420f00 [Max Power5 = 1000000]
Update field 53 = 0x0a000000 [Level = 10]
Update field 54 = 0x95060000 [FactionTemplate = 1685]
Update field 58 = 0x00030000 [UNIT_FIELD_FLAGS]
Update field 60 = 0x02100000 
Update field 61 = 0xd0070000 [Base Attack Time1 = 2000]
Update field 62 = 0xd0070000 [Base Attack Time2 = 2000]
Update field 64 = 0x0000403f
Update field 65 = 0x0000703f
Update field 66 = 0x61420000 [Display ID = 16993]
Update field 67 = 0x61420000 [Native Display ID = 16993]
Update field 73 = 0x07000000 [UNIT_FIELD_BYTES_1]
Update field 80 = 0x0000803f
Update field 120 = 0xc0000000
Update field 122 = 0x01000000 [UNIT_FIELD_BYTES_2]
Update field 146 = 0x0000803f

CMSG_CREATURE_QUERY
00000000:00000000 | 86 44 00 00 40 19 2d 86 44 00 30 f1             | .D..@.-.D.0.     | 

SMSG_CREATURE_QUERY_RESPONSE
00000000:00000000 | 86 44 00 00 59 6f 75 6e 67 20 46 75 72 62 6f 6c | .D..Young Furbol | 
00000000:00000010 | 67 20 53 68 61 6d 61 6e 00 00 00 00 00 00 00 00 | g Shaman........ | 
00000000:00000020 | 00 00 07 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ | 
00000000:00000030 | 00 00 61 42 00 00 00 00 00 00 00 00 00 00 00 00 | ..aB............ | 
00000000:00000040 | 00 00 00 00 80 3f 00 00 80 3f 00                | .....?...?.      | 

SMSG_SPELL_GO (Symbol of Life)
00000000:00000000 | 9f de 69 17 ba 01 40 0f XX XX XX XX eb 91 21 00 | ..i...@.......!. | 
00000000:00000010 | 00 10 01 00 00 f5 b1 48 7b 01 40 19 2d 86 44 00 | .......H{.@.-.D. | 
00000000:00000020 | 30 f1 00 02 00 00 00 00                         | 0.......         | 

SMSG_DESTROY_OBJECT
00000000:00000000 | de 69 17 ba 01 00 00 40 00                      | .i.....@.        | 

SMSG_SPELLHEALLOG
00000000:00000000 | df 40 19 2d 86 44 30 f1 df 40 19 2d 86 44 30 f1 | .@.-.D0..@.-.D0. | 
00000000:00000010 | 43 62 00 00 41 00 00 00 00 00 00 00 00 00       | Cb..A.........   | 

SMSG_SPELL_START
00000000:00000000 | df 40 19 2d 86 44 30 f1 df 40 19 2d 86 44 30 f1 | .@.-.D0..@.-.D0. | 
00000000:00000010 | 00 43 62 00 00 02 00 00 00 00 00 00 00 00 00 00 | .Cb............. | 
00000000:00000020 | 00                                              | .                | 

SMSG_SPELL_GO (Quest - Self Healing from resurrect)
00000000:00000000 | df 40 19 2d 86 44 30 f1 df 40 19 2d 86 44 30 f1 | .@.-.D0..@.-.D0. | 
00000000:00000010 | 00 43 62 00 00 00 01 00 00 0d da 48 7b 01 40 19 | .Cb........H{.@. | 
00000000:00000020 | 2d 86 44 00 30 f1 00 02 00 00 00 00             | -.D.0.......     | 

SMSG_UPDATE_OBJECT
GUID = 0xf1300044862d1940
Update field 23 = 0x42000000 [Health = 66]
Update field 73 = 0x00000000 [UNIT_FIELD_BYTES_1]

SMSG_SPELLENERGIZELOG
00000000:00000000 | df 40 19 2d 86 44 30 f1 df 40 19 2d 86 44 30 f1 | .@.-.D0..@.-.D0. | 
00000000:00000010 | 43 62 00 00 00 00 00 00 78 00 00 00             | Cb......x...     | 

SMSG_QUESTUPDATE_ADD_KILL
00000000:00000000 | 80 25 00 00 86 44 00 00 01 00 00 00 01 00 00 00 | .%...D.......... | 
00000000:00000010 | 00 00 00 00 00 00 00 00                         | ........         | 

SMSG_UPDATE_OBJECT
GUID = 0xf1300044862d1940
Update field 24 = 0x78000000 [Power1 = 120]
Update field 60 = 0x00000000

SMSG_MONSTER_MOVE
00000000:00000000 | df 40 19 2d 86 44 30 f1 79 ce 18 c5 55 b4 3e c6 | .@.-.D0.y...U.>. | 
00000000:00000010 | 02 8b 03 42 2c 4d c2 07 03 XX XX XX XX 00 00 00 | ...B,M.......... | 
00000000:00000020 | 00 00 01 00 00 00 00 00 00 01 00 00 00 79 ce 18 | .............y.. | 
00000000:00000030 | c5 55 b4 3e c6 02 8b 03 42                      | .U.>....B        | 

SMSG_MESSAGECHAT
00000000:00000000 | 10 00 00 00 00 40 19 2d 86 44 00 30 f1 00 00 00 | .....@.-.D.0.... | 
00000000:00000010 | 00 15 00 00 00 59 6f 75 6e 67 20 46 75 72 62 6f | .....Young Furbo | 
00000000:00000020 | 6c 67 20 53 68 61 6d 61 6e 00 XX XX XX XX 00 00 | lg Shaman....... | 
00000000:00000030 | 00 00 26 00 00 00 25 73 20 73 74 61 72 65 73 20 | ..&...%s stares  | 
00000000:00000040 | 61 74 20 79 6f 75 20 69 6e 20 73 68 65 65 72 20 | at you in sheer  | 
00000000:00000050 | 77 6f 6e 64 65 72 6d 65 6e 74 2e 00 00          | wonderment...    | 

SMSG_MESSAGECHAT
00000000:00000000 | 0c 00 00 00 00 40 19 2d 86 44 00 30 f1 00 00 00 | .....@.-.D.0.... | 
00000000:00000010 | 00 15 00 00 00 59 6f 75 6e 67 20 46 75 72 62 6f | .....Young Furbo | 
00000000:00000020 | 6c 67 20 53 68 61 6d 61 6e 00 40 19 2d 86 44 00 | lg Shaman.@.-.D. | 
00000000:00000030 | 30 f1 15 00 00 00 59 6f 75 6e 67 20 46 75 72 62 | 0.....Young Furb | 
00000000:00000040 | 6f 6c 67 20 53 68 61 6d 61 6e 00 0b 00 00 00 49 | olg Shaman.....I | 
00000000:00000050 | 20 72 75 6e 20 6e 6f 77 21 00 00                |  run now!..      | 

SMSG_MONSTER_MOVE
00000000:00000000 | df 40 19 2d 86 44 30 f1 79 ce 18 c5 55 b4 3e c6 | .@.-.D0.y...U.>. | 
00000000:00000010 | 02 8b 03 42 d5 5b c2 07 04 75 d5 88 40 00 01 00 | ...B.[...u..@... | 
00000000:00000020 | 00 00 00 00 00 01 00 00 00 79 ce 18 c5 55 b4 3e | .........y...U.> | 
00000000:00000030 | c6 02 8b 03 42                                  | ....B            | 

SMSG_MONSTER_MOVE
00000000:00000000 | df 40 19 2d 86 44 30 f1 79 ce 18 c5 55 b4 3e c6 | .@.-.D0.y...U.>. | 
00000000:00000010 | 02 8b 03 42 59 5f c2 07 00 00 01 00 00 d3 00 00 | ...BY_.......... | 
00000000:00000020 | 00 01 00 00 00 06 cb 18 c5 b4 bc 3e c6 07 7d 03 | ...........>..}. | 
00000000:00000030 | 42                                              | B                | 

SMSG_MONSTER_MOVE
00000000:00000000 | df 40 19 2d 86 44 30 f1 06 cb 18 c5 b4 bc 3e c6 | .@.-.D0.......>. | 
00000000:00000010 | 07 7d 03 42 59 62 c2 07 00 00 01 00 00 6b 05 00 | .}.BYb.......k.. | 
00000000:00000020 | 00 02 00 00 00 f5 b2 18 c5 ae f3 3e c6 0e fa fe | ...........>.... | 
00000000:00000030 | 41 ff ff ff ff  | A.... | 

SMSG_MONSTER_MOVE
00000000:00000000 | df 40 19 2d 86 44 30 f1 66 b6 18 c5 c8 eb 3e c6 | .@.-.D0.f.....>. | 
00000000:00000010 | 8c d9 ff 41 af 65 c2 07 00 00 01 00 00 1e 09 00 | ...A.e.......... | 
00000000:00000020 | 00 04 00 00 00 21 35 18 c5 cb 42 3f c6 a3 23 00 | .....!5...B?..#. | 
00000000:00000030 | 42 0e d8 fe ff 01 e8 7f 00 f2 17 c1 ff          | B............    | 

SMSG_MONSTER_MOVE
00000000:00000000 | df 40 19 2d 86 44 30 f1 39 79 18 c5 0a 18 3f c6 | .@.-.D0.9y....?. | 
00000000:00000010 | 9d 4f fa 41 0b 69 c2 07 00 00 01 00 00 d2 17 00 | .O.A.i.......... | 
00000000:00000020 | 00 0e 00 00 00 37 7f 17 c5 19 da 3f c6 c5 d6 dd | .....7.....?.... | 
00000000:00000030 | 41 11 00 7e fd 0d 48 3e fd 05 68 3e fd d3 77 7f | A..~..H>..h>..w. | 
00000000:00000040 | fd d0 d7 3f fe ce 0f 80 fe cc 4f 40 ff cb 7f 00 | ...?......O@.... | 
00000000:00000050 | 00 cb df c0 00 cb 07 01 01 cb 8f 41 01 cb 0f 02 | ...........A.... | 
00000000:00000060 | 01 cb 97 02 01                                  | .....            | 

SMSG_DESTROY_OBJECT
00000000:00000000 | 40 19 2d 86 44 00 30 f1 00                      | @.-.D.0..        | 
```

And I'm sorry, but so far I haven't found a trace of the other quests. I haven't played with paladins other than a draenei, so I guess I need to be reall lucky to find a sniff where I was nearby when a dwarf or human paladin was doing its quest...

**Comment by Grz3s** [comment]
@evil-at-wow thank you very much... this just proved what i said before...  hp = 1 ..bytes1 = 7 .. no aura .. no deathstate ... and whats important ... texts are diff also.
Only souprises is that he run off and desp after event.
Anyway nice job.

BTW:
Is there any option that i can get your sniff? ... would be easier me to read all that data.. for movement...
Or at least tell me whats the file name... i may have it already :P

**Comment by killerwife** [comment]
@evil-at-wow come by discord some time. I am adding support to TC parser for cmangos sniffs from tbc/wotlk and Idk if yours are from the same batch as maximuses.

**Comment by evil-at-wow** [comment]
@Grz3s I'll check this weekend what I can do for you. Be it prepare something in a format you could use, or translate the packets myself to usable data/coordinates, or whatever. I'm pretty sure you don't have that file already (unless you managed to hack my systems :wink: ), and giving it to you is not going to help you either I'm afraid.

The reason is that back in the days, I didn't know about any good publicly available data capture tools that worked properly on Linux, so I wrote my own set of tools. As a result, all data I have is using my own file format, and the TC parser or other tools would be useless for these files. I still regret not having put in the extra effort to make things compatible with existing tools later, because I have so much useful data to share. But things are what they are and I can't go back in time. Maybe some day I'll find the time to write a little converter or something.

@killerwife No, my data is not from a batch like that from Maximus. Pristine original data only here. That said, I agree I should come say hello one of these days. It's been too long.

**Comment by evil-at-wow** [comment]
@Grz3s I did some experiments last weekend and it looks like I'll be able to create a (pkt) file that Trinity's parser accepts from my data. At least it happily parsed my test file with 1 SMSG_MONSTER_MOVE packet and the data matches with what my tools spit out. There's a bit of work remaining to create a real file with all the packets, and I'll try to do that one of these days.

**Comment by evil-at-wow** [comment]
Ok, I just created a pkt file with all the packets I mentioned above, and then I realized I could as well dump the parser's output here instead of trying to find an easy way to share that binary file with you. I've downloaded the latest release version of their nightly builds and used that to parse the pkt file.

Full disclosure: Trinity's parser failed to parse two packets correctly near the end of the packet (SMSG_QUERY_CREATURE_RESPONSE and SMSG_SPELL_HEAL_LOG), and after some debugging and research I believe those are bugs in their parser for the version 3.0.9 structure. I have corrected these packets below. I'll open an issue for that in their repository later. Also note that the packet's time is *not* correct, so please ignore that. My conversion didn't write a tick count for every individual packet, so the parser seems to use the time stamp of the sniff for every packet. If you really need these time stamps, I can probably check manually, but for now I didn't want to spend more time on this. Here's the output:

```
# TrinityCore - WowPacketParser
# File name: redemption.pkt
# Detected build: V3_0_9_9551
# Detected locale: enGB
# Targeted database: WrathOfTheLichKing
# Parsing date: 08/18/2018 15:04:55

ClientToServer: CMSG_QUERY_CREATURE (0x0060) Length: 12 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 0
Entry: 17542 (17542)
GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584

ServerToClient: SMSG_QUERY_CREATURE_RESPONSE (0x0061) Length: 75 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 1
Entry: 17542
[0] Name: Young Furbolg Shaman
[1] Name: 
[2] Name: 
[3] Name: 
Sub Name: 
Icon Name: 
Type Flags: 0 (None)
Type: 7 (Humanoid)
Family: 0 (None)
Rank: 0 (Normal)
Pet Spell Data Id: 0
[0] Model ID: 16993
[1] Model ID: 0
[2] Model ID: 0
[3] Model ID: 0
Modifier 1: 1
Modifier 2: 1
Racial Leader: false

ServerToClient: SMSG_SPELL_START (0x0131) Length: 29 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 2
Caster GUID: Full: 0x40000001BA1769DE Type: Item Low: 7417063902
Caster Unit GUID: Full: 0x???????? Type: Player Low: ????????
Cast Count: 235
Spell ID: 8593 (8593)
Cast Flags: 18 (HasTrajectory, Unknown4)
Time: 10000
Target Flags: 0 (Self)

ServerToClient: SMSG_SPELL_GO (0x0132) Length: 40 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 3
Caster GUID: Full: 0x40000001BA1769DE Type: Item Low: 7417063902
Caster Unit GUID: Full: 0x???????? Type: Player Low: ????????
Cast Count: 235
Spell ID: 8593 (8593)
Cast Flags: 272 (Unknown4, Unknown7)
Time: 2068361717
Hit Count: 1
[0] Hit GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Miss Count: 0
Target Flags: 2 (Unit)
Target GUID: 0x0

ServerToClient: SMSG_DESTROY_OBJECT (0x00AA) Length: 9 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 4
GUID: Full: 0x40000001BA1769DE Type: Item Low: 7417063902
Despawn Animation: false

ServerToClient: SMSG_SPELL_HEAL_LOG (0x0150) Length: 30 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 5
Target GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Caster GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Spell ID: 25155 (25155)
Damage: 65
Overheal: 0
Critical: false

ServerToClient: SMSG_SPELL_START (0x0131) Length: 33 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 6
Caster GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Caster Unit GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Cast Count: 0
Spell ID: 25155 (25155)
Cast Flags: 2 (HasTrajectory)
Time: 0
Target Flags: 0 (Self)

ServerToClient: SMSG_SPELL_GO (0x0132) Length: 44 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 7
Caster GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Caster Unit GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Cast Count: 0
Spell ID: 25155 (25155)
Cast Flags: 256 (Unknown7)
Time: 2068371981
Hit Count: 1
[0] Hit GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Miss Count: 0
Target Flags: 2 (Unit)
Target GUID: 0x0

ServerToClient: SMSG_SPELL_ENERGIZE_LOG (0x0151) Length: 28 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 8
Target GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Caster GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Spell ID: 25155 (25155)
Power type: 0 (Mana)
Amount: 120

ServerToClient: SMSG_QUEST_UPDATE_ADD_KILL (0x0199) Length: 24 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 9
Quest ID: 9600 (9600)
Entry: 17542
Count: 1
Required Count: 1
GUID: 0x0

ServerToClient: SMSG_ON_MONSTER_MOVE (0x00DD) Length: 57 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 10
GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Position: X: -2444.905 Y: -12205.08 Z: 32.88575
Move Ticks: 130174252
Spline Type: 3 (FacingTarget)
Facing GUID: Full: 0x???????? Type: Player Low: ????????
Spline Flags: 256 (Done)
Move Time: 0
Waypoints: 1
Waypoint Endpoint: X: -2444.905 Y: -12205.08 Z: 32.88575

ServerToClient: SMSG_CHAT (0x0096) Length: 93 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 11
Type: 16 (MonsterEmote)
Language: 0 (Universal)
GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Constant time: 0
Name Length: 21
Name: Young Furbolg Shaman
Receiver GUID: Full: 0x???????? Type: Player Low: ????????
Text Length: 38
Text: %s stares at you in sheer wonderment.
Chat Tag: 0 (None)

ServerToClient: SMSG_CHAT (0x0096) Length: 91 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 12
Type: 12 (MonsterSay)
Language: 0 (Universal)
GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Constant time: 0
Name Length: 21
Name: Young Furbolg Shaman
Receiver GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Receiver Name Length: 21
Receiver Name: Young Furbolg Shaman
Text Length: 11
Text: I run now!
Chat Tag: 0 (None)

ServerToClient: SMSG_ON_MONSTER_MOVE (0x00DD) Length: 53 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 13
GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Position: X: -2444.905 Y: -12205.08 Z: 32.88575
Move Ticks: 130178005
Spline Type: 4 (FacingAngle)
Facing Angle: 4.276057
Spline Flags: 256 (Done)
Move Time: 0
Waypoints: 1
Waypoint Endpoint: X: -2444.905 Y: -12205.08 Z: 32.88575

ServerToClient: SMSG_ON_MONSTER_MOVE (0x00DD) Length: 49 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 14
GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Position: X: -2444.905 Y: -12205.08 Z: 32.88575
Move Ticks: 130178905
Spline Type: 0 (Normal)
Spline Flags: 256 (Done)
Move Time: 211
Waypoints: 1
Waypoint Endpoint: X: -2444.689 Y: -12207.18 Z: 32.8721

ServerToClient: SMSG_ON_MONSTER_MOVE (0x00DD) Length: 53 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 15
GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Position: X: -2444.689 Y: -12207.18 Z: 32.8721
Move Ticks: 130179673
Spline Type: 0 (Normal)
Spline Flags: 256 (Done)
Move Time: 1387
Waypoints: 2
Waypoint Endpoint: X: -2443.185 Y: -12220.92 Z: 31.8721
[1] Waypoint: X: -2443.687 Y: -12213.8 Z: 32.6221

ServerToClient: SMSG_ON_MONSTER_MOVE (0x00DD) Length: 61 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 16
GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Position: X: -2443.4 Y: -12218.95 Z: 31.98122
Move Ticks: 130180527
Spline Type: 0 (Normal)
Spline Flags: 256 (Done)
Move Time: 2334
Waypoints: 4
Waypoint Endpoint: X: -2435.321 Y: -12240.7 Z: 32.0348
[1] Waypoint: X: -2442.86 Y: -12220.57 Z: 32.25801
[2] Waypoint: X: -2439.61 Y: -12229.07 Z: 31.75801
[3] Waypoint: X: -2435.86 Y: -12238.32 Z: 32.25801

ServerToClient: SMSG_ON_MONSTER_MOVE (0x00DD) Length: 101 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 17
GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Position: X: -2439.576 Y: -12230.01 Z: 31.28887
Move Ticks: 130181387
Spline Type: 0 (Normal)
Spline Flags: 256 (Done)
Move Time: 6098
Waypoints: 14
Waypoint Endpoint: X: -2423.951 Y: -12278.52 Z: 27.72987
[1] Waypoint: X: -2436.014 Y: -12238.27 Z: 32.25937
[2] Waypoint: X: -2435.014 Y: -12240.52 Z: 32.50937
[3] Waypoint: X: -2433.014 Y: -12241.52 Z: 32.50937
[4] Waypoint: X: -2420.514 Y: -12249.77 Z: 32.25937
[5] Waypoint: X: -2419.764 Y: -12252.77 Z: 31.50937
[6] Waypoint: X: -2419.264 Y: -12254.52 Z: 31.00937
[7] Waypoint: X: -2418.764 Y: -12256.52 Z: 30.25937
[8] Waypoint: X: -2418.514 Y: -12258.02 Z: 29.50937
[9] Waypoint: X: -2418.514 Y: -12261.02 Z: 28.75937
[10] Waypoint: X: -2418.514 Y: -12262.27 Z: 28.50937
[11] Waypoint: X: -2418.514 Y: -12266.52 Z: 28.25937
[12] Waypoint: X: -2418.514 Y: -12270.52 Z: 28.50937
[13] Waypoint: X: -2418.514 Y: -12274.77 Z: 28.50937

ServerToClient: SMSG_DESTROY_OBJECT (0x00AA) Length: 9 ConnIdx: 0 Time: 02/15/2009 19:22:06.000 Number: 18
GUID: Full: 0xF1300044862D1940 Type: Creature Entry: 17542 Low: 2955584
Despawn Animation: false
```

**Comment by killerwife** [comment]
Well guess who added initial pre-3.1 commit :D It needs a lot more.

**Comment by offl** [comment]
Narm Faulk: https://www.youtube.com/watch?v=VKXoTRDmarY

**Comment by Grz3s** [comment]
hey... yes i've seen this one  ;)
ive got humans, dwarfs and draeneis done...
still missing data for (text + what happens after) for Blodd Elfs...

**Comment by offl** [comment]
Texts: http://www.members.iinet.net.au/~freddo_/public_html/WoW/bpquest14.jpg
I believe the blood elf's script is similar to draenei

**Comment by offl** [comment]
```sql
-- https://www.youtube.com/watch?v=KAIgaV6dK8Q & https://www.youtube.com/watch?v=bR-xmDJIzD4 & https://github.com/cmangos/issues/issues/1678
UPDATE `creature_template` SET `unit_flags2` = 0, `dynamicflags` = 0 WHERE `entry` = 17768;
UPDATE `creature_template_addon` SET `bytes2` = 1 WHERE `entry` = 17768;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 17768 AND `source_type` = 0;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 1776800 AND `source_type` = 9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(17768,0,0,0,8,0,100,1,31225,0,0,0,0,80,1776800,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"Blood Knight Stillblade - On Spellhit 'Shimmering Vessel' - Run Script (No Repeat)"),
(17768,0,1,0,40,0,100,0,8,0,0,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"Blood Knight Stillblade - On Waypoint 8 Reached - Despawn Instant"),

(1776800,9,0,0,0,0,100,0,0,0,0,0,0,91,7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"Blood Knight Stillblade - On Script - Remove Flag Standstate Dead"),
(1776800,9,1,0,0,0,100,0,0,0,0,0,0,11,25155,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"Blood Knight Stillblade - On Script - Cast 'Quest - Self Healing from resurrect'"),
(1776800,9,2,0,0,0,100,0,0,0,0,0,0,33,17768,0,0,0,0,0,7,0,0,0,0,0,0,0,0,"Blood Knight Stillblade - On Script - Quest Credit 'Redeeming the Dead'"),
(1776800,9,3,0,0,0,100,0,2000,2000,0,0,0,66,0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,"Blood Knight Stillblade - On Script - Set Orientation Invoker"),
(1776800,9,4,0,0,0,100,0,0,0,0,0,0,1,0,0,1,0,0,0,7,0,0,0,0,0,0,0,0,"Blood Knight Stillblade - On Script - Say Line 0"),
(1776800,9,5,0,0,0,100,0,6000,6000,0,0,0,1,1,0,1,0,0,0,7,0,0,0,0,0,0,0,0,"Blood Knight Stillblade - On Script - Say Line 1"),
(1776800,9,6,0,0,0,100,0,0,0,0,0,0,53,0,17768,0,0,0,3,1,0,0,0,0,0,0,0,0,"Blood Knight Stillblade - On Script - Start Waypoint");

DELETE FROM `waypoints` WHERE `entry` = 17768;
INSERT INTO `waypoints` (`entry`,`pointid`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`point_comment`) VALUES
(17768,1,9674.297852,-7375.656738,22.837454,0,0,"Blood Knight Stillblade"),
(17768,2,9682.087891,-7378.194824,22.844015,0,0,"Blood Knight Stillblade"),
(17768,3,9698.202148,-7378.187988,22.854086,0,0,"Blood Knight Stillblade"),
(17768,4,9702.776367,-7376.458496,20.979189,0,0,"Blood Knight Stillblade"),
(17768,5,9706.027344,-7370.661133,17.425856,0,0,"Blood Knight Stillblade"),
(17768,6,9704.005859,-7365.672363,14.453255,0,0,"Blood Knight Stillblade"),
(17768,7,9687.491211,-7366.161133,11.929653,0,0,"Blood Knight Stillblade"),
(17768,8,9683.428711,-7364.722656,11.931114,0,0,"Blood Knight Stillblade");
```
Didn't supported 1 hp and 0 mana yet(you do it differently any way) and wps are handmade

**Comment by AnonXS** [comment]
@AnonXS Reminder

**Comment by adellaci** [comment]
Confirmed Quest not Working
WoTLK
Core Hash Commit: 94812cdfcd7fbc896069d593f8ce363388125588
Database Commit: 94812cdfcd7fbc896069d593f8ce363388125588
Blood Elf, Paladin Quest
Redeeming the Dead Quest #9685
Using Item: Filled Shimmering Vessel # 24184
Use On; Blood Knight (Sangrias) Stillblade #17768 (Located in Silvermoon City (80.12, 60.28)
He resurrects, but does not get objective completion
If you abandon quest, Blood Knight (Sangrias) Stillblade #17768 does not reset/return to dead state

**Comment by killerwife** [comment]
Please recheck if TBC works as intended on the blood elf, then I will resolve the issue.

**Comment by confessore** [comment]
@killerwife confirmed working in:

[db @ 8d296e2](https://github.com/cmangos/tbc-db/tree/8d296e2d59260082d22d2c339d4a6ad2aed162e7)
[mangos @ 42f9174](https://github.com/cmangos/mangos-tbc/tree/42f917417271c59764b4e485f0d84a2e38191e66)

<img width="242" alt="image" src="https://user-images.githubusercontent.com/1919812/171778556-55f4605e-335c-4c7c-9e4d-fd8e931ee023.png">

**Comment by AnonXS** [comment]
resolved.
