### ISSUE TITLE
🐛 [Bug Report]Compile error WOTLK

### ISSUE THREAD

**Issue by Orcman2019** [cmangos/issues#2100]
[ 82%] Building CXX object src/game/CMakeFiles/game.dir/Entities/Object.cpp.o
[ 83%] Building CXX object src/game/CMakeFiles/game.dir/Entities/ObjectGuid.cpp.                                                                                                                                                             o
[ 83%] Building CXX object src/game/CMakeFiles/game.dir/Entities/ObjectVisibilit                                                                                                                                                             y.cpp.o
In file included from /home/cmangos/mangostemp/src/game/Entities/ObjectVisibilit                                                                                                                                                             y.cpp:19:0:
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:22:1: warning: ela                                                                                                                                                             borated-type-specifier for a scoped enum must not use the ‘class’ keyword
 enum class VisibilityDistanceType : uint32
 ^~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:22:12: error: use                                                                                                                                                              of enum ‘VisibilityDistanceType’ without previous declaration
 enum class VisibilityDistanceType : uint32
            ^~~~~~~~~~~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:22:35: error: expe                                                                                                                                                             cted unqualified-id before ‘:’ token
 enum class VisibilityDistanceType : uint32
                                   ^
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:34:6: error: use o                                                                                                                                                             f enum ‘StealthType’ without previous declaration
 enum StealthType : uint32
      ^~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:34:18: error: expe                                                                                                                                                             cted unqualified-id before ‘:’ token
 enum StealthType : uint32
                  ^
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:41:6: error: use o                                                                                                                                                             f enum ‘InvisibilityType’ without previous declaration
 enum InvisibilityType : uint32
      ^~~~~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:41:23: error: expe                                                                                                                                                             cted unqualified-id before ‘:’ token
 enum InvisibilityType : uint32
                       ^
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:51:35: error: expe                                                                                                                                                             cted ‘)’ before ‘*’ token
         VisibilityData(WorldObject* owner);
                                   ^
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:55:44: error: ‘Vis                                                                                                                                                             ibilityDistanceType’ has not been declared
         void SetVisibilityDistanceOverride(VisibilityDistanceType type);
                                            ^~~~~~~~~~~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:58:40: error: ‘Wor                                                                                                                                                             ldObject’ has not been declared
         float GetVisibilityDistanceFor(WorldObject* obj) const;
                                        ^~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:60:38: error: ‘Wor                                                                                                                                                             ldObject’ has not been declared
         bool CanDetectInvisibilityOf(WorldObject const* u) const;
                                      ^~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:61:9: error: ‘uint                                                                                                                                                             32’ does not name a type; did you mean ‘rintf32’?
         uint32 GetInvisibilityDetectMask() const;
         ^~~~~~
         rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:62:40: error: ‘uin                                                                                                                                                             t32’ has not been declared
         void SetInvisibilityDetectMask(uint32 index, bool apply);
                                        ^~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:63:9: error: ‘uint                                                                                                                                                             32’ does not name a type; did you mean ‘rintf32’?
         uint32 GetInvisibilityMask() const;
         ^~~~~~
         rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:64:34: error: ‘uin                                                                                                                                                             t32’ has not been declared
         void SetInvisibilityMask(uint32 index, bool apply);
                                  ^~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:65:35: error: ‘uin                                                                                                                                                             t32’ has not been declared
         void SetInvisibilityValue(uint32 index, int32 value) { m_invisibilityVa                                                                                                                                                             lues[index] = value; }
                                   ^~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:65:49: error: ‘int                                                                                                                                                             32’ has not been declared
         void SetInvisibilityValue(uint32 index, int32 value) { m_invisibilityVa                                                                                                                                                             lues[index] = value; }
                                                 ^~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:66:35: error: ‘uin                                                                                                                                                             t32’ has not been declared
         void AddInvisibilityValue(uint32 index, int32 value) { m_invisibilityVa                                                                                                                                                             lues[index] += value; }
                                   ^~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:66:49: error: ‘int                                                                                                                                                             32’ has not been declared
         void AddInvisibilityValue(uint32 index, int32 value) { m_invisibilityVa                                                                                                                                                             lues[index] += value; }
                                                 ^~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:67:41: error: ‘uin                                                                                                                                                             t32’ has not been declared
         void AddInvisibilityDetectValue(uint32 index, int32 value) { m_invisibi                                                                                                                                                             lityDetectValues[index] += value; }
                                         ^~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:67:55: error: ‘int                                                                                                                                                             32’ has not been declared
         void AddInvisibilityDetectValue(uint32 index, int32 value) { m_invisibi                                                                                                                                                             lityDetectValues[index] += value; }
                                                       ^~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:68:9: error: ‘int3                                                                                                                                                             2’ does not name a type; did you mean ‘intf’?
         int32 GetInvisibilityValue(uint32 index) const;
         ^~~~~
         intf
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:69:9: error: ‘int3                                                                                                                                                             2’ does not name a type; did you mean ‘intf’?
         int32 GetInvisibilityDetectValue(uint32 index) const;
         ^~~~~
         intf
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:71:9: error: ‘uint                                                                                                                                                             32’ does not name a type; did you mean ‘rintf32’?
         uint32 GetStealthMask() const { return m_stealthMask; }
         ^~~~~~
         rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:72:29: error: ‘uin                                                                                                                                                             t32’ has not been declared
         void SetStealthMask(uint32 index, bool apply);
                             ^~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:73:33: error: ‘Ste                                                                                                                                                             althType’ has not been declared
         void AddStealthStrength(StealthType type, uint32 value) { m_stealthStre                                                                                                                                                             ngth[type] += value; }
                                 ^~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:73:51: error: ‘uin                                                                                                                                                             t32’ has not been declared
         void AddStealthStrength(StealthType type, uint32 value) { m_stealthStre                                                                                                                                                             ngth[type] += value; }
                                                   ^~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:74:42: error: ‘Ste                                                                                                                                                             althType’ has not been declared
         void AddStealthDetectionStrength(StealthType type, uint32 value) { m_st                                                                                                                                                             ealthDetectStrength[type] += value; }
                                          ^~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:74:60: error: ‘uin                                                                                                                                                             t32’ has not been declared
         void AddStealthDetectionStrength(StealthType type, uint32 value) { m_st                                                                                                                                                             ealthDetectStrength[type] += value; }
                                                            ^~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:75:9: error: ‘uint                                                                                                                                                             32’ does not name a type; did you mean ‘rintf32’?
         uint32 GetStealthStrength(StealthType type) const { return m_stealthStr                                                                                                                                                             ength[type]; }
         ^~~~~~
         rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:76:9: error: ‘uint                                                                                                                                                             32’ does not name a type; did you mean ‘rintf32’?
         uint32 GetStealthDetectionStrength(StealthType type) const { return m_s                                                                                                                                                             tealthDetectStrength[type]; }
         ^~~~~~
         rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:78:44: error: ‘Uni                                                                                                                                                             t’ has not been declared
         float GetStealthVisibilityDistance(Unit const* target, bool alert = fal                                                                                                                                                             se) const;
                                            ^~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:83:9: error: ‘uint                                                                                                                                                             32’ does not name a type; did you mean ‘rintf32’?
         uint32 m_invisibilityMask;
         ^~~~~~
         rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:84:9: error: ‘uint                                                                                                                                                             32’ does not name a type; did you mean ‘rintf32’?
         uint32 m_detectInvisibilityMask; // is inherited from controller in PC                                                                                                                                                              case
         ^~~~~~
         rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:85:9: error: ‘int3                                                                                                                                                             2’ does not name a type; did you mean ‘intf’?
         int32 m_invisibilityValues[INVISIBILITY_TYPE_MAX];
         ^~~~~
         intf
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:86:9: error: ‘int3                                                                                                                                                             2’ does not name a type; did you mean ‘intf’?
         int32 m_invisibilityDetectValues[INVISIBILITY_TYPE_MAX];
         ^~~~~
         intf
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:88:9: error: ‘uint                                                                                                                                                             32’ does not name a type; did you mean ‘rintf32’?
         uint32 m_stealthMask;
         ^~~~~~
         rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:89:9: error: ‘uint                                                                                                                                                             32’ does not name a type; did you mean ‘rintf32’?
         uint32 m_stealthStrength[STEALTH_TYPE_MAX];
         ^~~~~~
         rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:90:9: error: ‘uint                                                                                                                                                             32’ does not name a type; did you mean ‘rintf32’?
         uint32 m_stealthDetectStrength[STEALTH_TYPE_MAX];
         ^~~~~~
         rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:92:9: error: ‘Worl                                                                                                                                                             dObject’ does not name a type; did you mean ‘SN_dcObject’?
         WorldObject* m_owner;
         ^~~~~~~~~~~
         SN_dcObject
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h: In member functio                                                                                                                                                             n ‘void VisibilityData::SetInvisibilityValue(int, int)’:
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:65:64: error: ‘m_i                                                                                                                                                             nvisibilityValues’ was not declared in this scope
         void SetInvisibilityValue(uint32 index, int32 value) { m_invisibilityVa                                                                                                                                                             lues[index] = value; }
                                                                ^~~~~~~~~~~~~~~~                                                                                                                                                             ~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:65:64: note: sugge                                                                                                                                                             sted alternative: ‘SetInvisibilityValue’
         void SetInvisibilityValue(uint32 index, int32 value) { m_invisibilityVa                                                                                                                                                             lues[index] = value; }
                                                                ^~~~~~~~~~~~~~~~                                                                                                                                                             ~~~~
                                                                SetInvisibilityV                                                                                                                                                             alue
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h: In member functio                                                                                                                                                             n ‘void VisibilityData::AddInvisibilityValue(int, int)’:
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:66:64: error: ‘m_i                                                                                                                                                             nvisibilityValues’ was not declared in this scope
         void AddInvisibilityValue(uint32 index, int32 value) { m_invisibilityVa                                                                                                                                                             lues[index] += value; }
                                                                ^~~~~~~~~~~~~~~~                                                                                                                                                             ~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:66:64: note: sugge                                                                                                                                                             sted alternative: ‘SetInvisibilityValue’
         void AddInvisibilityValue(uint32 index, int32 value) { m_invisibilityVa                                                                                                                                                             lues[index] += value; }
                                                                ^~~~~~~~~~~~~~~~                                                                                                                                                             ~~~~
                                                                SetInvisibilityV                                                                                                                                                             alue
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h: In member functio                                                                                                                                                             n ‘void VisibilityData::AddInvisibilityDetectValue(int, int)’:
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:67:70: error: ‘m_i                                                                                                                                                             nvisibilityDetectValues’ was not declared in this scope
        void AddInvisibilityDetectValue(uint32 index, int32 value) { m_invisibil                                                                                                                                                             ityDetectValues[index] += value; }
                                                                     ^~~~~~~~~~~                                                                                                                                                             ~~~~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:67:70: note: sugge                                                                                                                                                             sted alternative: ‘AddInvisibilityDetectValue’
        void AddInvisibilityDetectValue(uint32 index, int32 value) { m_invisibil                                                                                                                                                             ityDetectValues[index] += value; }
                                                                     ^~~~~~~~~~~                                                                                                                                                             ~~~~~~~~~~~~~~~
                                                                      AddInvisib                                                                                                                                                             ilityDetectValue
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h: In member functio                                                                                                                                                             n ‘void VisibilityData::AddStealthStrength(int, int)’:
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:73:67: error: ‘m_s                                                                                                                                                             tealthStrength’ was not declared in this scope
         void AddStealthStrength(StealthType type, uint32 value) { m_stealthStre                                                                                                                                                             ngth[type] += value; }
                                                                   ^~~~~~~~~~~~~                                                                                                                                                             ~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:73:67: note: sugge                                                                                                                                                             sted alternative: ‘AddStealthStrength’
         void AddStealthStrength(StealthType type, uint32 value) { m_stealthStre                                                                                                                                                             ngth[type] += value; }
                                                                   ^~~~~~~~~~~~~                                                                                                                                                             ~~~~
                                                                   AddStealthStr                                                                                                                                                             ength
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h: In member functio                                                                                                                                                             n ‘void VisibilityData::AddStealthDetectionStrength(int, int)’:
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:74:76: error: ‘m_s                                                                                                                                                             tealthDetectStrength’ was not declared in this scope
  void AddStealthDetectionStrength(StealthType type, uint32 value) { m_stealthDe                                                                                                                                                             tectStrength[type] += value; }
                                                                     ^~~~~~~~~~~                                                                                                                                                             ~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.h:74:76: note: sugge                                                                                                                                                             sted alternative: ‘AddStealthDetectionStrength’
  void AddStealthDetectionStrength(StealthType type, uint32 value) { m_stealthDe                                                                                                                                                             tectStrength[type] += value; }
                                                                     ^~~~~~~~~~~                                                                                                                                                             ~~~~~~~~~~~~
                                                                            AddS                                                                                                                                                             tealthDetectionStrength
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp: At global scope                                                                                                                                                             :
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:21:54: error: ‘V                                                                                                                                                             isibilityDistanceType’ has not been declared
 constexpr float VisibilityDistances[AsUnderlyingType(VisibilityDistanceType::Ma                                                                                                                                                             x)] =
                                                      ^~~~~~~~~~~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:21:37: error: ‘A                                                                                                                                                             sUnderlyingType’ was not declared in this scope
 constexpr float VisibilityDistances[AsUnderlyingType(VisibilityDistanceType::Ma                                                                                                                                                             x)] =
                                     ^~~~~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:21:37: note: sug                                                                                                                                                             gested alternative: ‘__underlying_type’
 constexpr float VisibilityDistances[AsUnderlyingType(VisibilityDistanceType::Ma                                                                                                                                                             x)] =
                                     ^~~~~~~~~~~~~~~~
                                     __underlying_type
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:23:5: error: ‘DE                                                                                                                                                             FAULT_VISIBILITY_DISTANCE’ was not declared in this scope
     DEFAULT_VISIBILITY_DISTANCE,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:24:5: error: ‘VI                                                                                                                                                             SIBILITY_DISTANCE_TINY’ was not declared in this scope
     VISIBILITY_DISTANCE_TINY,
     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:25:5: error: ‘VI                                                                                                                                                             SIBILITY_DISTANCE_SMALL’ was not declared in this scope
     VISIBILITY_DISTANCE_SMALL,
     ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:26:5: error: ‘VI                                                                                                                                                             SIBILITY_DISTANCE_LARGE’ was not declared in this scope
     VISIBILITY_DISTANCE_LARGE,
     ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:27:5: error: ‘VI                                                                                                                                                             SIBILITY_DISTANCE_GIGANTIC’ was not declared in this scope
     VISIBILITY_DISTANCE_GIGANTIC,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:28:5: error: ‘MA                                                                                                                                                             X_VISIBILITY_DISTANCE’ was not declared in this scope
     MAX_VISIBILITY_DISTANCE
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:31:31: error: ex                                                                                                                                                             pected constructor, destructor, or type conversion before ‘(’ token
 VisibilityData::VisibilityData(WorldObject* owner) : m_visibilityDistanceOverri                                                                                                                                                             de(0.f), m_invisibilityMask(0), m_detectInvisibilityMask(0), m_owner(owner)
                               ^
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:40:52: error: va                                                                                                                                                             riable or field ‘SetVisibilityDistanceOverride’ declared void
 void VisibilityData::SetVisibilityDistanceOverride(VisibilityDistanceType type)
                                                    ^~~~~~~~~~~~~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:40:52: error: ‘V                                                                                                                                                             isibilityDistanceType’ was not declared in this scope
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:40:52: note: sug                                                                                                                                                             gested alternative: ‘VisibilityData’
 void VisibilityData::SetVisibilityDistanceOverride(VisibilityDistanceType type)
                                                    ^~~~~~~~~~~~~~~~~~~~~~
                                                    VisibilityData
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp: In member funct                                                                                                                                                             ion ‘float VisibilityData::GetVisibilityDistance() const’:
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:54:16: error: ‘m                                                                                                                                                             _owner’ was not declared in this scope
         return m_owner->GetMap()->GetVisibilityDistance();
                ^~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:54:16: note: sug                                                                                                                                                             gested alternative: ‘SN_owner’
         return m_owner->GetMap()->GetVisibilityDistance();
                ^~~~~~~
                SN_owner
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp: At global scope                                                                                                                                                             :
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:57:48: error: ‘f                                                                                                                                                             loat VisibilityData::GetVisibilityDistanceFor’ is not a static data member of ‘c                                                                                                                                                             lass VisibilityData’
 float VisibilityData::GetVisibilityDistanceFor(WorldObject* obj) const
                                                ^~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:57:48: error: ‘W                                                                                                                                                             orldObject’ was not declared in this scope
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:57:48: note: sug                                                                                                                                                             gested alternative: ‘SN_dcObject’
 float VisibilityData::GetVisibilityDistanceFor(WorldObject* obj) const
                                                ^~~~~~~~~~~
                                                SN_dcObject
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:57:61: error: ‘o                                                                                                                                                             bj’ was not declared in this scope
 float VisibilityData::GetVisibilityDistanceFor(WorldObject* obj) const
                                                             ^~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:65:58: error: ‘b                                                                                                                                                             ool VisibilityData::CanDetectInvisibilityOf’ is not a static data member of ‘cla                                                                                                                                                             ss VisibilityData’
 bool VisibilityData::CanDetectInvisibilityOf(WorldObject const* target) const
                                                          ^~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:65:46: error: ‘W                                                                                                                                                             orldObject’ was not declared in this scope
 bool VisibilityData::CanDetectInvisibilityOf(WorldObject const* target) const
                                              ^~~~~~~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:65:46: note: sug                                                                                                                                                             gested alternative: ‘SN_dcObject’
 bool VisibilityData::CanDetectInvisibilityOf(WorldObject const* target) const
                                              ^~~~~~~~~~~
                                              SN_dcObject
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:88:1: error: ‘ui                                                                                                                                                             nt32’ does not name a type; did you mean ‘rintf32’?
 uint32 VisibilityData::GetInvisibilityDetectMask() const
 ^~~~~~
 rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:103:48: error: v                                                                                                                                                             ariable or field ‘SetInvisibilityDetectMask’ declared void
 void VisibilityData::SetInvisibilityDetectMask(uint32 index, bool apply)
                                                ^~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:103:48: error:                                                                                                                                                               uint32’ was not declared in this scope
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:103:48: note: su                                                                                                                                                             ggested alternative: ‘rintf32’
 void VisibilityData::SetInvisibilityDetectMask(uint32 index, bool apply)
                                                ^~~~~~
                                                rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:103:62: error: e                                                                                                                                                             xpected primary-expression before ‘bool’
 void VisibilityData::SetInvisibilityDetectMask(uint32 index, bool apply)
                                                              ^~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:111:1: error: ‘u                                                                                                                                                             int32’ does not name a type; did you mean ‘rintf32’?
 uint32 VisibilityData::GetInvisibilityMask() const
 ^~~~~~
 rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:116:42: error: v                                                                                                                                                             ariable or field ‘SetInvisibilityMask’ declared void
 void VisibilityData::SetInvisibilityMask(uint32 index, bool apply)
                                          ^~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:116:42: error:                                                                                                                                                               uint32’ was not declared in this scope
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:116:42: note: su                                                                                                                                                             ggested alternative: ‘rintf32’
 void VisibilityData::SetInvisibilityMask(uint32 index, bool apply)
                                          ^~~~~~
                                          rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:116:56: error: e                                                                                                                                                             xpected primary-expression before ‘bool’
 void VisibilityData::SetInvisibilityMask(uint32 index, bool apply)
                                                        ^~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:124:1: error: ‘i                                                                                                                                                             nt32’ does not name a type; did you mean ‘intf’?
 int32 VisibilityData::GetInvisibilityValue(uint32 index) const
 ^~~~~
 intf
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:129:1: error: ‘i                                                                                                                                                             nt32’ does not name a type; did you mean ‘intf’?
 int32 VisibilityData::GetInvisibilityDetectValue(uint32 index) const
 ^~~~~
 intf
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:145:37: error: v                                                                                                                                                             ariable or field ‘SetStealthMask’ declared void
 void VisibilityData::SetStealthMask(uint32 index, bool apply)
                                     ^~~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:145:37: error:                                                                                                                                                               uint32’ was not declared in this scope
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:145:37: note: su                                                                                                                                                             ggested alternative: ‘rintf32’
 void VisibilityData::SetStealthMask(uint32 index, bool apply)
                                     ^~~~~~
                                     rintf32
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:145:51: error: e                                                                                                                                                             xpected primary-expression before ‘bool’
 void VisibilityData::SetStealthMask(uint32 index, bool apply)
                                                   ^~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:153:57: error:                                                                                                                                                               float VisibilityData::GetStealthVisibilityDistance’ is not a static data member                                                                                                                                                              of ‘class VisibilityData’
 float VisibilityData::GetStealthVisibilityDistance(Unit const* target, bool ale                                                                                                                                                             rt) const
                                                         ^~~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:153:52: error:                                                                                                                                                               Unit’ was not declared in this scope
 float VisibilityData::GetStealthVisibilityDistance(Unit const* target, bool ale                                                                                                                                                             rt) const
                                                    ^~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:153:52: note: su                                                                                                                                                             ggested alternative: ‘exit’
 float VisibilityData::GetStealthVisibilityDistance(Unit const* target, bool ale                                                                                                                                                             rt) const
                                                    ^~~~
                                                    exit
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:153:72: error: e                                                                                                                                                             xpected primary-expression before ‘bool’
 at VisibilityData::GetStealthVisibilityDistance(Unit const* target, bool alert)                                                                                                                                                              const
                                                                     ^~~~
/home/cmangos/mangostemp/src/game/Entities/ObjectVisibility.cpp:153:82: error: e                                                                                                                                                             xpression list treated as compound expression in initializer [-fpermissive]
 ibilityData::GetStealthVisibilityDistance(Unit const* target, bool alert) const
                                                                         ^
src/game/CMakeFiles/game.dir/build.make:13883: recipe for target 'src/game/CMake                                                                                                                                                             Files/game.dir/Entities/ObjectVisibility.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/Entities/ObjectVisibility.cpp.o] Erro                                                                                                                                                             r 1
CMakeFiles/Makefile2:546: recipe for target 'src/game/CMakeFiles/game.dir/all' f                                                                                                                                                             ailed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

### Version & Environment
"3.3.5a" (WOTLK)
Client Version: 
https://github.com/cmangos/mangos-wotlk/tree/0f25acc14be82ba267e74ae69b58b4de41f52849
DB 
https://github.com/cmangos/wotlk-db/tree/7637ca7fd06d6bca218b4de2caa5ad4742ab27c5
Operating System: Linux Mint 19.2

**Comment by ekg98** [comment]
Missing a header?

**Comment by evil-at-wow** [comment]
It's the same issue we also had in the TBC branch a few weeks ago after a bunch of exports. It looks like not all of those commits are in the WoTLK branch yet, so I think killerwife is still busy porting commits (so I'm sure this should be fixed soon-ish). While it's unfortunate that he didn't take the fixes at the same time as the relevant commits and thus pushed a broken state, I can imagine that's easy to forget because it's hard to keep track of.

If you want a build now, apply a patch like cmangos/mangos-tbc@c3d26a8729.

**Comment by Orcman2019** [comment]
Makes sense, I can wait a bit I guess... Just saw all the shiny new changes and was hoping paladin auras might be working now.

**Comment by Orcman2019** [comment]
Hmm well those additions let it compile, ran for about 10 minutes and crashed like #2096

**Comment by Grz3s** [comment]
can you pls check with this?:
`UPDATE creature_template SET extraFlags=extraFlags&~4096;`
you may receive some errors ...but thats not important ... just check if server still crashes

**Comment by Orcman2019** [comment]
Trying it out
