### ISSUE TITLE
🐛 [Bug Report] Memory leak

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3265]
### Bug Details

The server needs to be restarted every three days. Because the memory is full, the system does not respond and cannot log in remotely. 

![image](https://user-images.githubusercontent.com/3367999/208697568-3ee6466f-8bcb-434e-8308-2ffe97cd74be.png)

Server Information:
OS: Ubuntu 20.04.4 LTS
Hardware: 4Core 8G RAM
Number of online players per day: less than 15
Compilation option: with AHBot (no Player robot)
Mangos related configuration: GridUnload=1

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

7d38c3e8a91feeb97d2ec9e3ad110d5d7c911337

### Database SHA1 Commit Hash

153612cab10c07fda019d59269d1831fd83fa113

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by evil-at-wow** [comment]
I think another - and in this case possibly more relevant - configuration is mmap.enabled. But my educated guess is that you have "mmap.enabled = 1" in your configuration, correct? 

Either way, I noticed some leaks as well - you may have noticed that I have fixed a handful of them already recently - and I'm slowly working on getting some more fixed, even though I can't say yet if they explain what you're seeing here.

**Comment by aleigood** [comment]
> I think another - and in this case possibly more relevant - configuration is mmap.enabled. But my educated guess is that you have "mmap.enabled = 1" in your configuration, correct?
> 
> Either way, I noticed some leaks as well - you may have noticed that I have fixed a handful of them already recently - and I'm slowly working on getting some more fixed, even though I can't say yet if they explain what you're seeing here.

Thank you for paying attention to this problem. I have seen the relevant fix you submitted, and I have also upgraded in time. As you said, I used mmap The default configuration , It is enabled. At present, it seems that the memory leak may be caused in other places than the database. I can provide other information if required.

**Comment by adellaci** [comment]
[https://github.com/cmangos/issues/issues/3140](url)
Similar issue as this one. I still can't load all with out running out of memory. I don't have an idea how far back the mem leak started.

**Comment by evil-at-wow** [comment]
I've seen that one as well but if I understood correctly, that was mostly (only?) a problem when having grids loaded all the time, while in this case it seems to slowly eat memory even with default settings. Both are a problem of course, it's just that I started fixing the issues I also noticed first. Once we're done with that we can tackle the next ones...

**Comment by adellaci** [comment]
I use to run months without restarting and have all grids loaded

Dec 22, 2022 10:42:39 evil-at-wow ***@***.***>:

**Comment by Grz3s** [comment]
AS i said before... having everything loaded is a huge waste of RAM etc... 
All my scripts are made to max. saving PC resourcess .. and loading only if players are near (kept active for whole circle - and then unload self if poss). theyre few exceptions from it ofc.. like Hellfire Peninsula Dark Portal inviasion , kwadir invasion in Borean Tundra and few others - these must be loaded all the time... and we using special EXtraFlag for it.

I might be wrong ofc... but if so.. then explain me what is the point to keep anything active in Mulgore if 0 Players are there ?

**Comment by adellaci** [comment]
At one point I had a use for it. No need to explain more. Now I use it for testing. The system I have can more then handle it. Dedicated Dell PowerEdge 2900 fully decked out

Dec 22, 2022 11:21:53 Grz3s ***@***.***>:

**Comment by evil-at-wow** [comment]
I've pushed another memory leak fix - see cmangos/mangos-tbc@29a3a38ad2568e76 - but it was far more "static" (in the sense it's not leaking continously) than I initially thought, so I highly doubt this is going to change anything for this issue.

There's another memory leak that shows more potential, to say so, because it typically happens every time a player logs in, but the involved objects are rather small so I'm also not convinced this will significantly improve things. Your graph shows an increased memory use of a few gigabytes in a few days, which would probably be like a few million player logins, which sounds rather unrealistic. Either way, I have a very experimental fix for that one as well (see link to the PR here), but I wouldn't suggest to run that in production yet...

There's one more memory leak with some potential on my list that I'll investigate, so let's see what that one brings. To be continued!

**Comment by aleigood** [comment]
> I've pushed another memory leak fix - see [cmangos/mangos-tbc@29a3a38ad2568e76](https://github.com/cmangos/mangos-tbc/commit/29a3a38ad2568e76) - but it was far more "static" (in the sense it's not leaking continously) than I initially thought, so I highly doubt this is going to change anything for this issue.
> 
> There's another memory leak that shows more potential, to say so, because it typically happens every time a player logs in, but the involved objects are rather small so I'm also not convinced this will significantly improve things. Your graph shows an increased memory use of a few gigabytes in a few days, which would probably be like a few million player logins, which sounds rather unrealistic. Either way, I have a very experimental fix for that one as well (see link to the PR here), but I wouldn't suggest to run that in production yet...
> 
> There's one more memory leak with some potential on my list that I'll investigate, so let's see what that one brings. To be continued!

It has been applied to the server, and I will keep tracking.

**Comment by aleigood** [comment]
![image](https://user-images.githubusercontent.com/3367999/209459252-de8f4ffc-b430-4d69-815e-62ddc4f05477.png)

From the blue curve, we can see the growth rate of memory usage. The server crashed twice around 16:00 (the reason is not clear at present), so there was an obvious decline. Then the memory usage rose straightly. At 1:00 a.m. on December 25, another crash occurred, making the memory usage return to the low point. I cut the memory growth curve (red) before the update for the same time period and compared it with the growth curve after the update. It can be found that the growth rate of memory usage is basically the same, so the conclusion is that there is no significant improvement.

**Comment by evil-at-wow** [comment]
Thank you for following up and confirming what I already suspected!

**Comment by evil-at-wow** [comment]
Well, the "one more memory leak with some potential" turned out to be two different ones. I pushed a few more changes related to memory leaks to the TBC core, and I'm expecting these to have more impact than previous ones because they happen "continuously" as the core is running. Yet I'm still not entirely convinced they fully explain the large growth you are seeing, but I have no others left on my list, so we'll see how it goes :smile:

**Comment by rmzV** [comment]
wotlk have same problem..

maybe its related to ahh bot?

**Comment by evil-at-wow** [comment]
The wrath core does not have any of the memory leak fixes I did in the TBC branch yet, so that's certainly not helping there.
I also have no feedback yet whether my last fixes (see my last comment above) made any noticeable difference, so just maybe the problem is already fixed in the TBC. It's also possible it only improved a bit and it's not fixed. At least I don't see the problem on my own TBC test server any more when running it for a few hours, but perhaps a few hours is not long enough.
We'll have to see when feedback comes and investigate further if needed.

**Comment by rmzV** [comment]
@evil-at-wow 
its mostly days problem; server starts with 3 gb load, now after 2? days its 5gb memory load.

**Comment by evil-at-wow** [comment]
Yes, I understand the problem is more a matter of days and not hours because the effect is cumulative so the problem gets bigger over time, but my point is that there's not much the server is doing in 2 days that it isn't also doing in 3 hours or so. So if I see zero leaks now after 3 hours, I would expect zero leaks after 2 days as well (this isn't exactly accurate, I know there are still some very small ones, but in the order of KB rather than MB as before which is practically speaking near zero). If that's not the case, then something happens on those servers that's not happening during my tests, and we'll investigate further. But as I mentioned, for now only TBC cores are expected to have improved in this area with the other cores waiting for backports.

**Comment by al3xc1985** [comment]
@aleigood can u do some tests now, after so many improvements?

**Comment by rmzV** [comment]
wotlk build with ahh bot  from may 10, leaks was still in place(

UPD june 6 still persists

**Comment by evil-at-wow** [comment]
With a build of May 10 that is not unexpected, because it is missing several memory leak fixes I commited in the Wrath branch on May 12, so you're at least missing those. But more importantly, we're also missing a recent change that was a very nice find and that I believe has a significant impact, but is still only in Classic (see cmangos/mangos-classic@5c64aab6a404d5e1ea36bb20a77866848bdefdcf) and is awaiting a port to other branches.

That said, thank you very much for checking and reporting back! We'll keep working on this to improve things.

**Comment by adellaci** [comment]
@evil-at-wow 
With the crash fix, i started an other memory leak test with AutoLoad.Active =1, and GridUnload = 0

**Comment by aleigood** [comment]
I apologize for not providing feedback on this issue for a long time. In fact, due to other frustrating issues such as random disconnections and loss of player data, my server has been left unattended, and I haven't had the opportunity to compare the data under the same conditions. Currently, there are occasional players logging into my server, but after running for three to four days, the memory is still getting filled up. I have updated the code to the latest version this week, and it can be seen that the memory usage percentage is growing faster than before (my server configuration has not changed, and only cmangos-tbc is running).
![屏幕截图 2023-06-17 173120](https://github.com/cmangos/issues/assets/3367999/db6c8e94-c384-4abb-a4de-ebbe1932b9ab)

**Comment by al3xc1985** [comment]
@adellaci any news?

**Comment by rmzV** [comment]
@al3xc1985 
as windows user, i did next:
1) created 2 *.bat files for starting server and closing server
2) use windows schedule tool to load this scripts at 5 am and 5:20 am

**Comment by al3xc1985** [comment]
any news? it is fixed?

**Comment by evil-at-wow** [comment]
According to the recent report in https://github.com/cmangos/issues/issues/2358#issuecomment-2676176495, where memory goes from ~2,5 GB to ~8,5 GB in a week, there's still some work remaining (or perhaps new regressions) to be looked at. So let's keep this open for now.

**Comment by miraco** [comment]
I had my server now running for 5 days and 7 hours with valgrind on.

<img width="971" height="128" alt="Image" src="https://github.com/user-attachments/assets/854521f4-3695-4e6f-af4d-7e766a53217e" />

It started with 3.7g and i ended it with 10.3g

<img width="965" height="114" alt="Image" src="https://github.com/user-attachments/assets/d1ba9f5a-d7e4-4df9-9a54-a1cca8bd8ed9" />

<img width="936" height="121" alt="Image" src="https://github.com/user-attachments/assets/ff38c07e-fa16-4ebb-8f6d-e08632cde7ed" />

> ==250714== LEAK SUMMARY:
> ==250714==    definitely lost: 2,385,980 bytes in 613,984 blocks
> ==250714==    indirectly lost: 19,169 bytes in 54 blocks
> ==250714==      possibly lost: 7,948 bytes in 23 blocks
> ==250714==    still reachable: 661,024,559 bytes in 5,729,231 blocks
> ==250714==                       of which reachable via heuristic:
> ==250714==                         multipleinheritance: 384 bytes in 24 blocks
> ==250714==         suppressed: 0 bytes in 0 blocks

If you want i can share the complete log with you.
