### ISSUE TITLE
🐛 [Bug Report] [TBC] CoT: Dark Portal Dungeon rifts not spawning mobs

### ISSUE THREAD

**Issue by steppnasty** [cmangos/issues#3974]
### Bug Details

In the Dark Portal instance, once the event is started, the first rift is opened but no mobs are spawned.

### Steps to Reproduce

1. Enter Dark Portal/Black Morass instance
2. Get close enough to Medivh to trigger event
3. First rift will open, no mobs will spawn in.
4.

### Expected behavior

Once the first rift opens, a Rift Keeper or Rift Lord will spawn in momentarily and other mobs will periodically spawn in while it is alive.

### Suggested Workaround

Looks like TimeRiftPeriodic should be an AuraScript and not a SpellScript. 

Made the following local change in src/game/AI/ScriptDevAI/scripts/kalimdor/caverns_of_time/dark_portal/dark_portalScripts.cpp to fix the issue:

```
@@ -370,11 +370,11 @@ UnitAI* GetAI_npc_time_rift(Creature* pCreature)
 }

 // 31320 - Time Rift Periodic
-struct TimeRiftPeriodic : public SpellScript
+struct TimeRiftPeriodic : public AuraScript
 {
-    void OnEffectExecute(Spell* spell, SpellEffectIndex effIdx) const override
+    void OnPeriodicTrigger(Aura* aura, PeriodicTriggerData& data) const override
     {
-        Unit* target = spell->GetUnitTarget();
+        Unit* target = aura->GetTarget();
         if (npc_time_riftAI* timeRiftAI = dynamic_cast<npc_time_riftAI*>(target->AI()))
             timeRiftAI->DoSummon();
     }

```

### Core SHA1 Commit Hash

86b75739388a10b5de12ca8ba780f6b327f4a92b

### Database SHA1 Commit Hash

1a31fcc6a1f68c61eb592614bd634b3f0ca4c315

### Operating System

Ubuntu 24.04 Server

### Client Version

2.4.3 (The Burning Crusade)

**Comment by cpevors** [comment]
Oof. Can reproduce. Not sure what changed; I did this dungeon a couple/few weeks ago, to my recollection, without issues.

**Comment by AnonXS** [comment]
just a guess but maybe some staticflags?

https://github.com/cmangos/tbc-db/commit/dec8392b25a439a73bd1658a99ea288a6e7e30ef

15608 is part of this commit.

we should also review `SELECT * FROM creature_template WHERE CreatureTypeFlags&0x00000002 order by entry;` because they are different between classic,tbc and wotlk.

**Comment by steppnasty** [comment]
There were a few recent commits for refactoring spell scripts.  
cmangos/mangos-tbc@91a72eecb6c8b7f9c9ca0f1d817f510994e4dac1

Fixed the case notes above so the diff is readable.  As spell 31320 is an Aura in the db, TimeRiftPeriodic->OnEffectExecute does not get called because it is a SpellScript.  Switching it to an AuraScript seems to work.

**Comment by killerwife** [comment]
Please make a PR. The suggested code is correct from my quick check.

**Comment by Szymplo** [comment]
Hey Masters. I know all u have private life and so on ;) But I strongly Need Black Morass Working right
mangos-tbc 45b8912824e98034fd5d4bdab2ab713b2443e65d
tbc-db          0afa2ec8919d25fca6ca165a30a6a21f05c198de

The problem still exist. Plz assist

Best Regards

**Comment by junkb0x** [comment]
Pulled latest of the core & updated the server, this issue still persists. 
I hope it can get updated soon :)
