### ISSUE TITLE
Servercrash when Voidwalker autocasts sacrifice

### ISSUE THREAD

**Issue by Elemental85** [cmangos/issues#961]
**Current behavior**: 
Server crashes when a warlock has his void walker out, sets sacrifice to autocast and gives his void walker an attack command.

**Expected behavior**: 
no crash, but actually the autocast doesn't make sense at all, turning it off won't hurt anyone

**Steps to reproduce**:

1. as Warlock summon your Voidwalker, make sure it has the ability "sacrifice"
2. set sacrifice to autocast (rightclick)
3. target an enemy and let your voidwalker attack it (CTRL+1)

**Client version**: 
1.12.1

**Commit hash**: 
still downloaded on June 5th 2016 with the applied hotfix for resummoning Warlock pets

**Database version**: 
UDB Classic

**Operating system**: 
Windows 10 (Crash Log identifies it as Windows 8, but it is 10.0.10586)

Debugging it with Visual Studio Pro 2015 breaks at line 159 in Object.h

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

Revision: * * *
Date 13:6:2016. Time 2:23 
//=====================================================
*** Hardware ***
Processor: Intel(R) Celeron(R) CPU  N3150  @ 1.60GHz
Number Of Processors: 4
Physical Memory: 16435292 KB (Available: 13102900 KB)
Commit Charge Limit: 18925660 KB

*** Operation System ***
Windows 8 (Version 6.2, Build 9200)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00000001400D402A 01:00000000000D302A C:\WoW\Run\mangosd.exe

Registers:
RAX:00007FF5EB8B8100
RBX:00007FF5EB8B8100
RCX:0000000000000000
RDX:0000000000000000
RSI:00007FF5EBE4E080
RDI:00007FF5DB2D5940
R8: 00007FFD5050CDC4
R9: 00007FF5EA14ADAE
R10:000000000669FAA0
R11:00007FF5DB2D5940
R12:00007FF5EA149FE0
R13:00007FF5DD09D600
R14:0000000000000002
R15:0000000000000001
CS:RIP:0033:00000001400D402A
SS:RSP:002B:000000000669FAB0  RBP:0669FC30
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010202

Call stack:
Address   Frame     Function      SourceFile
00000001400D402A  000000000669FAE0  Unit::isTargetableForAttack+A  c:\wow\mangos\src\game\unit.cpp line 6371
000000014031AA19  000000000669FB20  PetAI::_needToStop+99  c:\wow\mangos\src\game\petai.cpp line 102
000000014031A48C  000000000669FC80  PetAI::UpdateAI+9AC  c:\wow\mangos\src\game\petai.cpp line 331
00000001400DEC20  000000000669FCC0  Creature::Update+350  c:\wow\mangos\src\game\creature.cpp line 588
00000001400FD0CF  000000000669FD00  Pet::Update+15F  c:\wow\mangos\src\game\pet.cpp line 663
00000001400F0C03  000000000669FD30  MaNGOS::ObjectUpdater::Visit+83  c:\wow\mangos\src\game\gridnotifiersimpl.h line 46
00000001400F0574  000000000669FDF0  Map::Update+4A4  c:\wow\mangos\src\game\map.cpp line 508
00000001401D8357  000000000669FE40  MapManager::Update+67  c:\wow\mangos\src\game\mapmanager.cpp line 175
0000000140087AFF  000000000669FE80  World::Update+13F  c:\wow\mangos\src\game\world.cpp line 1374
000000014005D311  000000000669FEB0  WorldRunnable::run+61  c:\wow\mangos\src\mangosd\worldrunnable.cpp line 66
0000000140078EF5  000000000669FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl*)(void * __ptr64),void * __ptr64>,std::default_delete<std::tuple<void (__cdecl*)(void * __ptr64),void * __ptr64> > > >::_Run+75  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000669FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000669FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000669FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000669FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5764  000000000014F850  NtDelayExecution+14
00007FFD54EB38C7  000000000014F8F0  SleepEx+A7
00007FFD3E0D1F7C  000000000014F940  _Thrd_sleep+3C
0000000140054C24  000000000014F990  std::this_thread::sleep_for<__int64,std::ratio<1,1> >+84  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thread line 154
000000014005799C  000000000014FD20  Master::Run+82C  c:\wow\mangos\src\mangosd\master.cpp line 231
000000014005382D  000000000014FF10  main+A2D  c:\wow\mangos\src\mangosd\main.cpp line 201
000000014005FCF8  000000000014FF50  __scrt_common_main_seh+124  f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl line 264
00007FFD56F48102  000000000014FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000014FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5764  00000000022DFD40  NtDelayExecution+14
00007FFD54EB38C7  00000000022DFDE0  SleepEx+A7
00007FFD3E0D1F7C  00000000022DFE30  _Thrd_sleep+3C
0000000140078E42  00000000022DFE80  MaNGOS::Thread::Sleep+82  c:\wow\mangos\src\shared\threading.cpp line 137
000000014007B20A  00000000022DFEB0  SqlDelayThread::run+4A  c:\wow\mangos\src\shared\database\sqldelaythread.cpp line 50
0000000140078EF5  00000000022DFEF0  std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl*)(void * __ptr64),void * __ptr64>,std::default_delete<std::tuple<void (__cdecl*)(void * __ptr64),void * __ptr64> > > >::_Run+75  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  00000000022DFF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  00000000022DFF50  _crt_at_quick_exit+7D
00007FFD56F48102  00000000022DFF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  00000000022DFFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5764  00000000023DFD40  NtDelayExecution+14
00007FFD54EB38C7  00000000023DFDE0  SleepEx+A7
00007FFD3E0D1F7C  00000000023DFE30  _Thrd_sleep+3C
0000000140078E42  00000000023DFE80  MaNGOS::Thread::Sleep+82  c:\wow\mangos\src\shared\threading.cpp line 137
000000014007B20A  00000000023DFEB0  SqlDelayThread::run+4A  c:\wow\mangos\src\shared\database\sqldelaythread.cpp line 50
0000000140078EF5  00000000023DFEF0  std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl*)(void * __ptr64),void * __ptr64>,std::default_delete<std::tuple<void (__cdecl*)(void * __ptr64),void * __ptr64> > > >::_Run+75  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  00000000023DFF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  00000000023DFF50  _crt_at_quick_exit+7D
00007FFD56F48102  00000000023DFF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  00000000023DFFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5764  00000000024DFD40  NtDelayExecution+14
00007FFD54EB38C7  00000000024DFDE0  SleepEx+A7
00007FFD3E0D1F7C  00000000024DFE30  _Thrd_sleep+3C
0000000140078E42  00000000024DFE80  MaNGOS::Thread::Sleep+82  c:\wow\mangos\src\shared\threading.cpp line 137
000000014007B20A  00000000024DFEB0  SqlDelayThread::run+4A  c:\wow\mangos\src\shared\database\sqldelaythread.cpp line 50
0000000140078EF5  00000000024DFEF0  std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl*)(void * __ptr64),void * __ptr64>,std::default_delete<std::tuple<void (__cdecl*)(void * __ptr64),void * __ptr64> > > >::_Run+75  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  00000000024DFF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  00000000024DFF50  _crt_at_quick_exit+7D
00007FFD56F48102  00000000024DFF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  00000000024DFFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB6D54  000000000669DD60  NtGetContextThread+14
00007FFD54ED9F0A  000000000669DD90  GetThreadContext+A
000000014005EB9E  000000000669E2C0  WheatyExceptionReport::printTracesForAllThreads+BE  c:\wow\mangos\src\shared\wheatyexceptionreport.cpp line 281
000000014005DC92  000000000669E950  WheatyExceptionReport::GenerateExceptionReport+322  c:\wow\mangos\src\shared\wheatyexceptionreport.cpp line 380
000000014005E4F8  000000000669EBF0  WheatyExceptionReport::WheatyUnhandledExceptionFilter+148  c:\wow\mangos\src\shared\wheatyexceptionreport.cpp line 107
00007FFD54F37E1E  000000000669ECF0  UnhandledExceptionFilter+1AE
00007FFD57DBD998  000000000669ED30  memset+2098
00007FFD57DA5B26  000000000669EDA0  __C_specific_handler+96
00007FFD57DB9AFD  000000000669EDD0  __chkstk+FD
00007FFD57D44FE9  000000000669F4E0  RtlImageNtHeaderEx+4B9
00007FFD57DB8C0A  000000000669FAA0  KiUserExceptionDispatcher+3A
00000001400D402A  000000000669FAE0  Unit::isTargetableForAttack+A  c:\wow\mangos\src\game\unit.cpp line 6371
000000014031AA19  000000000669FB20  PetAI::_needToStop+99  c:\wow\mangos\src\game\petai.cpp line 102
000000014031A48C  000000000669FC80  PetAI::UpdateAI+9AC  c:\wow\mangos\src\game\petai.cpp line 331
00000001400DEC20  000000000669FCC0  Creature::Update+350  c:\wow\mangos\src\game\creature.cpp line 588
00000001400FD0CF  000000000669FD00  Pet::Update+15F  c:\wow\mangos\src\game\pet.cpp line 663
00000001400F0C03  000000000669FD30  MaNGOS::ObjectUpdater::Visit+83  c:\wow\mangos\src\game\gridnotifiersimpl.h line 46
00000001400F0574  000000000669FDF0  Map::Update+4A4  c:\wow\mangos\src\game\map.cpp line 508
00000001401D8357  000000000669FE40  MapManager::Update+67  c:\wow\mangos\src\game\mapmanager.cpp line 175
0000000140087AFF  000000000669FE80  World::Update+13F  c:\wow\mangos\src\game\world.cpp line 1374
000000014005D311  000000000669FEB0  WorldRunnable::run+61  c:\wow\mangos\src\mangosd\worldrunnable.cpp line 66
0000000140078EF5  000000000669FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl*)(void * __ptr64),void * __ptr64>,std::default_delete<std::tuple<void (__cdecl*)(void * __ptr64),void * __ptr64> > > >::_Run+75  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000669FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000669FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000669FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000669FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB51A4  000000000679FA50  ZwReadFile+14
00007FFD54E8C324  000000000679FAD0  ReadFile+74
00007FFD53536A67  000000000679FB70  _read+427
00007FFD53536718  000000000679FBB0  _read+D8
00007FFD5354F740  000000000679FBE0  ungetwc+150
00007FFD5353D0B1  000000000679FC30  fgetpos+E1
000000014004C93E  000000000679FEB0  CliRunnable::run+13E  c:\wow\mangos\src\mangosd\clirunnable.cpp line 617
0000000140078EF5  000000000679FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl*)(void * __ptr64),void * __ptr64>,std::default_delete<std::tuple<void (__cdecl*)(void * __ptr64),void * __ptr64> > > >::_Run+75  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000679FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000679FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000679FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000679FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5204  000000000689FCF0  ZwRemoveIoCompletion+14
00007FFD54EC17A2  000000000689FD50  GetQueuedCompletionStatus+52
000000014005A472  000000000689FE40  boost::asio::detail::win_iocp_io_service::do_one+1C2  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 367
000000014005B7DD  000000000689FEA0  boost::asio::detail::win_iocp_io_service::run+AD  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 164
0000000140058A66  000000000689FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> >,std::default_delete<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> > > > >::_Run+86  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000689FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000689FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000689FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000689FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5764  000000000699FD40  NtDelayExecution+14
00007FFD54EB38C7  000000000699FDE0  SleepEx+A7
00007FFD3E0D1F7C  000000000699FE30  _Thrd_sleep+3C
0000000140057FB4  000000000699FEB0  MaNGOS::NetworkThread<WorldSocket>::SocketCleanupWork+154  c:\wow\mangos\src\shared\network\networkthread.hpp line 128
0000000140058867  000000000699FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> >,std::default_delete<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> > > > >::_Run+77  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000699FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000699FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000699FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000699FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5204  0000000006A9FCF0  ZwRemoveIoCompletion+14
00007FFD54EC17A2  0000000006A9FD50  GetQueuedCompletionStatus+52
000000014005A472  0000000006A9FE40  boost::asio::detail::win_iocp_io_service::do_one+1C2  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 367
000000014005B7DD  0000000006A9FEA0  boost::asio::detail::win_iocp_io_service::run+AD  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 164
0000000140058A66  0000000006A9FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> >,std::default_delete<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> > > > >::_Run+86  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  0000000006A9FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  0000000006A9FF50  _crt_at_quick_exit+7D
00007FFD56F48102  0000000006A9FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  0000000006A9FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5764  0000000006B9FD40  NtDelayExecution+14
00007FFD54EB38C7  0000000006B9FDE0  SleepEx+A7
00007FFD3E0D1F7C  0000000006B9FE30  _Thrd_sleep+3C
0000000140057FB4  0000000006B9FEB0  MaNGOS::NetworkThread<WorldSocket>::SocketCleanupWork+154  c:\wow\mangos\src\shared\network\networkthread.hpp line 128
0000000140058867  0000000006B9FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> >,std::default_delete<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> > > > >::_Run+77  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  0000000006B9FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  0000000006B9FF50  _crt_at_quick_exit+7D
00007FFD56F48102  0000000006B9FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  0000000006B9FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5204  0000000006C9FCF0  ZwRemoveIoCompletion+14
00007FFD54EC17A2  0000000006C9FD50  GetQueuedCompletionStatus+52
000000014005A472  0000000006C9FE40  boost::asio::detail::win_iocp_io_service::do_one+1C2  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 367
000000014005B7DD  0000000006C9FEA0  boost::asio::detail::win_iocp_io_service::run+AD  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 164
0000000140058A66  0000000006C9FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> >,std::default_delete<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> > > > >::_Run+86  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  0000000006C9FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  0000000006C9FF50  _crt_at_quick_exit+7D
00007FFD56F48102  0000000006C9FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  0000000006C9FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5764  0000000006D9FD40  NtDelayExecution+14
00007FFD54EB38C7  0000000006D9FDE0  SleepEx+A7
00007FFD3E0D1F7C  0000000006D9FE30  _Thrd_sleep+3C
0000000140057FB4  0000000006D9FEB0  MaNGOS::NetworkThread<WorldSocket>::SocketCleanupWork+154  c:\wow\mangos\src\shared\network\networkthread.hpp line 128
0000000140058867  0000000006D9FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> >,std::default_delete<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> > > > >::_Run+77  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  0000000006D9FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  0000000006D9FF50  _crt_at_quick_exit+7D
00007FFD56F48102  0000000006D9FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  0000000006D9FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5204  0000000006E9FCF0  ZwRemoveIoCompletion+14
00007FFD54EC17A2  0000000006E9FD50  GetQueuedCompletionStatus+52
000000014005A472  0000000006E9FE40  boost::asio::detail::win_iocp_io_service::do_one+1C2  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 367
000000014005B7DD  0000000006E9FEA0  boost::asio::detail::win_iocp_io_service::run+AD  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 164
0000000140058A66  0000000006E9FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> >,std::default_delete<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> > > > >::_Run+86  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  0000000006E9FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  0000000006E9FF50  _crt_at_quick_exit+7D
00007FFD56F48102  0000000006E9FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  0000000006E9FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5764  0000000006F9FD40  NtDelayExecution+14
00007FFD54EB38C7  0000000006F9FDE0  SleepEx+A7
00007FFD3E0D1F7C  0000000006F9FE30  _Thrd_sleep+3C
0000000140057FB4  0000000006F9FEB0  MaNGOS::NetworkThread<WorldSocket>::SocketCleanupWork+154  c:\wow\mangos\src\shared\network\networkthread.hpp line 128
0000000140058867  0000000006F9FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> >,std::default_delete<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> > > > >::_Run+77  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  0000000006F9FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  0000000006F9FF50  _crt_at_quick_exit+7D
00007FFD56F48102  0000000006F9FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  0000000006F9FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5204  000000000709FCF0  ZwRemoveIoCompletion+14
00007FFD54EC17A2  000000000709FD50  GetQueuedCompletionStatus+52
000000014005A472  000000000709FE40  boost::asio::detail::win_iocp_io_service::do_one+1C2  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 367
000000014005B7C2  000000000709FEA0  boost::asio::detail::win_iocp_io_service::run+92  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 164
0000000140058A66  000000000709FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> >,std::default_delete<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> > > > >::_Run+86  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000709FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000709FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000709FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000709FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5764  000000000719FD40  NtDelayExecution+14
00007FFD54EB38C7  000000000719FDE0  SleepEx+A7
00007FFD3E0D1F7C  000000000719FE30  _Thrd_sleep+3C
0000000140057FB4  000000000719FEB0  MaNGOS::NetworkThread<WorldSocket>::SocketCleanupWork+154  c:\wow\mangos\src\shared\network\networkthread.hpp line 128
0000000140058867  000000000719FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> >,std::default_delete<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> > > > >::_Run+77  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000719FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000719FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000719FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000719FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5204  000000000729FCF0  ZwRemoveIoCompletion+14
00007FFD54EC17A2  000000000729FD50  GetQueuedCompletionStatus+52
000000014005A472  000000000729FE40  boost::asio::detail::win_iocp_io_service::do_one+1C2  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 367
000000014005B7C2  000000000729FEA0  boost::asio::detail::win_iocp_io_service::run+92  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 164
0000000140058A66  000000000729FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> >,std::default_delete<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> > > > >::_Run+86  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000729FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000729FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000729FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000729FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5764  000000000739FD40  NtDelayExecution+14
00007FFD54EB38C7  000000000739FDE0  SleepEx+A7
00007FFD3E0D1F7C  000000000739FE30  _Thrd_sleep+3C
0000000140057FB4  000000000739FEB0  MaNGOS::NetworkThread<WorldSocket>::SocketCleanupWork+154  c:\wow\mangos\src\shared\network\networkthread.hpp line 128
0000000140058867  000000000739FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> >,std::default_delete<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> > > > >::_Run+77  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000739FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000739FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000739FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000739FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5204  000000000749FCF0  ZwRemoveIoCompletion+14
00007FFD54EC17A2  000000000749FD50  GetQueuedCompletionStatus+52
000000014005A472  000000000749FE40  boost::asio::detail::win_iocp_io_service::do_one+1C2  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 367
000000014005B7C2  000000000749FEA0  boost::asio::detail::win_iocp_io_service::run+92  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 164
0000000140058A66  000000000749FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> >,std::default_delete<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> > > > >::_Run+86  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000749FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000749FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000749FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000749FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5764  000000000759FD40  NtDelayExecution+14
00007FFD54EB38C7  000000000759FDE0  SleepEx+A7
00007FFD3E0D1F7C  000000000759FE30  _Thrd_sleep+3C
0000000140057FB4  000000000759FEB0  MaNGOS::NetworkThread<WorldSocket>::SocketCleanupWork+154  c:\wow\mangos\src\shared\network\networkthread.hpp line 128
0000000140058867  000000000759FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> >,std::default_delete<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> > > > >::_Run+77  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000759FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000759FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000759FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000759FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5204  000000000769FCF0  ZwRemoveIoCompletion+14
00007FFD54EC17A2  000000000769FD50  GetQueuedCompletionStatus+52
000000014005A472  000000000769FE40  boost::asio::detail::win_iocp_io_service::do_one+1C2  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 367
000000014005B7C2  000000000769FEA0  boost::asio::detail::win_iocp_io_service::run+92  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 164
0000000140058A66  000000000769FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> >,std::default_delete<std::tuple<<lambda_d5a1af83da781995a75817cd324ae7b5> > > > >::_Run+86  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000769FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000769FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000769FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000769FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5764  000000000779FD40  NtDelayExecution+14
00007FFD54EB38C7  000000000779FDE0  SleepEx+A7
00007FFD3E0D1F7C  000000000779FE30  _Thrd_sleep+3C
0000000140057FB4  000000000779FEB0  MaNGOS::NetworkThread<WorldSocket>::SocketCleanupWork+154  c:\wow\mangos\src\shared\network\networkthread.hpp line 128
0000000140058867  000000000779FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> >,std::default_delete<std::tuple<<lambda_0dc145a3134cc73ab01f0b3c740edef0> > > > >::_Run+77  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000779FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000779FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000779FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000779FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5164  000000000789FE10  ZwWaitForSingleObject+14
00007FFD54E8AADF  000000000789FEB0  WaitForSingleObjectEx+8F
000000014006A340  000000000789FEE0  boost::asio::detail::win_iocp_io_service::timer_thread_function::operator()+30  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 54
000000014006DDDF  000000000789FF20  boost::asio::detail::win_thread_function+2F  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_thread.ipp line 120
00007FFD5353BE1D  000000000789FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000789FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000789FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5204  000000000799FCF0  ZwRemoveIoCompletion+14
00007FFD54EC17A2  000000000799FD50  GetQueuedCompletionStatus+52
000000014005A472  000000000799FE40  boost::asio::detail::win_iocp_io_service::do_one+1C2  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 367
000000014005B7DD  000000000799FEA0  boost::asio::detail::win_iocp_io_service::run+AD  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 164
00000001400589B3  000000000799FEF0  std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_b187550f433136e733ff26a2426f2473> >,std::default_delete<std::tuple<<lambda_b187550f433136e733ff26a2426f2473> > > > >::_Run+93  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 245
0000000140023BB9  000000000799FF20  std::_Pad::_Call_func+9  c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread line 208
00007FFD5353BE1D  000000000799FF50  _crt_at_quick_exit+7D
00007FFD56F48102  000000000799FF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  000000000799FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5164  00000000080DFE10  ZwWaitForSingleObject+14
00007FFD54E8AADF  00000000080DFEB0  WaitForSingleObjectEx+8F
000000014006A340  00000000080DFEE0  boost::asio::detail::win_iocp_io_service::timer_thread_function::operator()+30  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 54
000000014006DDDF  00000000080DFF20  boost::asio::detail::win_thread_function+2F  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_thread.ipp line 120
00007FFD5353BE1D  00000000080DFF50  _crt_at_quick_exit+7D
00007FFD56F48102  00000000080DFF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  00000000080DFFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5164  00000000082DFE10  ZwWaitForSingleObject+14
00007FFD54E8AADF  00000000082DFEB0  WaitForSingleObjectEx+8F
000000014006A340  00000000082DFEE0  boost::asio::detail::win_iocp_io_service::timer_thread_function::operator()+30  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 54
000000014006DDDF  00000000082DFF20  boost::asio::detail::win_thread_function+2F  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_thread.ipp line 120
00007FFD5353BE1D  00000000082DFF50  _crt_at_quick_exit+7D
00007FFD56F48102  00000000082DFF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  00000000082DFFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFD57DB5164  00000000083DFE10  ZwWaitForSingleObject+14
00007FFD54E8AADF  00000000083DFEB0  WaitForSingleObjectEx+8F
000000014006A340  00000000083DFEE0  boost::asio::detail::win_iocp_io_service::timer_thread_function::operator()+30  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_iocp_io_service.ipp line 54
000000014006DDDF  00000000083DFF20  boost::asio::detail::win_thread_function+2F  c:\wow\boost_1_61_0\boost\asio\detail\impl\win_thread.ipp line 120
00007FFD5353BE1D  00000000083DFF50  _crt_at_quick_exit+7D
00007FFD56F48102  00000000083DFF80  BaseThreadInitThunk+22
00007FFD57D6C5B4  00000000083DFFD0  RtlUserThreadStart+34
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
00000001400D402A  000000000669FAE0  Unit::isTargetableForAttack+A  c:\wow\mangos\src\game\unit.cpp line 6371

000000014031AA19  000000000669FB20  PetAI::_needToStop+99  c:\wow\mangos\src\game\petai.cpp line 102

000000014031A48C  000000000669FC80  PetAI::UpdateAI+9AC  c:\wow\mangos\src\game\petai.cpp line 331
	Local  <user defined> 'victim'
	Local  <user defined> 'owner'
punting on symbol minRange
punting on symbol spell_id
punting on symbol spellInfo
punting on symbol result

**Comment by Phatcat** [comment]
@Elemental85 Have you applied the hotfix I just pushed today to master?
https://github.com/cmangos/mangos-classic/commit/01f536532d714b14d2fbf51a37612478630be6a3

**Comment by Elemental85** [comment]
sry, no I didn't ... I came home and my friend reported the crash

**Comment by Phatcat** [comment]
Don't worry, I just thought to ask since you were so nice and specific about which version and what commits from the core you were using =) - You can close this one yourself when you have verified that it fixes the issue on your server, or just poke me and I'll do it =)

**Comment by Elemental85** [comment]
ok, thanks for your help, my friend and I highly appreciate it :)

**Comment by Elemental85** [comment]
I hate to tell this, the server crashed again. I just downloaded an recompiled the current version and double checked if the change from https://github.com/cmangos/mangos-classic/commit/01f536532d714b14d2fbf51a37612478630be6a3 was applied (it is).

So it seems the bug is still there, sorry -.-

**Comment by Phatcat** [comment]
Don't be sorry, this is actually why we chose to roll it out, to get some wider feedback on it.

**Comment by Elemental85** [comment]
I can only thank you for your time and effort :)

**Comment by Phatcat** [comment]
Just gotta reproduce it myself, then I can hopefully get to the bottom of it...

**Comment by Phatcat** [comment]
@Elemental85
I cannot reproduce on latest master, could you perhaps try updating as [this](https://github.com/cmangos/mangos-classic/commit/8504123fb4a8382b651a6967dd8a1e7c3473d4d5) could have solved it. If you are still experiencing the issue then I need more details on how you reproduce this.

Perhaps if this is an old character you may have to reset your talents as cala reported this on the pr where I did the pet rework;

>Warlock

> After unlearning talents, the warlock I used for tests was able to make his pet casts a spell on a target without crash. Relearning the exact same talents did not make the crash reappears. Strange

**Comment by Elemental85** [comment]
ok, I'll try it and report back as soon as possible.thanks :)

**Comment by Elemental85** [comment]
Works fine now, didn't need to unlearn anything :)
thanks again ^^

**Comment by Phatcat** [comment]
You can thank @Oniryck for that one ;)

**Comment by Elemental85** [comment]
done ^^
wish I was a little bit better with c++ ... I do some programming in c# but well ... .Net is for lazy people I guess xD
